# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Αρχική
    url: /
    weight: 10
  - name: Μάθε να οδηγάς
    url: docs/
    weight: 20
  - name: Η μηχανή
    url: showcase/
    weight: 30
  - name: Service
    url: service/
    weight: 40
  - name: Blog
    url: blog/
    weight: 50


# sidebar:
#   - identifier: more
#     name: Still need help?
#     params:
#       type: separator
#     weight: 1
#   - identifier: community
#     name: "Community"
#     pageRef: "/community"
#     weight: 2
#   - identifier: hugoDocs
#     name: "Hugo Docs ↗"
#     url: "https://docs.hugoblox.com"
#     weight: 3
